---
abstract: ~
author:
  - 'Denny de la Haye <2014@denny.me>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ShinyCMS
no_index:
  directory:
    - inc
    - t
recommends:
  FCGI: 0
  FCGI::ProcManager: 0
  Template::Plugin::Markdown: 0
requires:
  Archive::Any: '0.03'
  CGI::Ajax: '0.707'
  CGI::Cookie: '1.20'
  Captcha::reCAPTCHA: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Realm::SimpleDB: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::DBIC: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: '5.80004'
  Catalyst::TraitFor::Request::BrowserDetect: 0
  Catalyst::View::Email: 0
  Catalyst::View::TT: 0
  CatalystX::RoleApplicator: 0
  Config::General: 0
  DBD::mysql: '4.046'
  DBIx::Class::EncodedColumn: 0
  DBIx::Class::Schema::Loader: 0
  DBIx::Class::TimeStamp: 0
  Doorman: '0.10'
  Email::Sender: '0.102360'
  Email::Valid: 0
  File::NCopy: '0.32'
  File::Pid: 0
  File::Remove: '0.20'
  File::Temp: '0.2304'
  HTML::Restrict: 0
  HTML::TreeBuilder: 0
  Lingua::EN::NameParse: '1.36'
  Method::Signatures::Simple: 0
  MooseX::MarkAsMethods: 0
  MooseX::NonMoose: 0
  Net::Domain::TLD: 0
  String::Random: '0.29'
  Term::VT102::Boundless: '0.04'
  Term::VT102::Incremental: '0.05'
  Text::CSV::Simple: 0
  XML::Feed: 0
  parent: 0
version: '0.007'
